# Generated by Django 5.2.8 on 2025-11-30 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options_postattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='контент комментарий')),
                ('time_stamp', models.TimeField(default=django.utils.timezone.now, verbose_name='дата и время')),
                ('edited', models.BooleanField(default=False, verbose_name='изменен ли пост?')),
                ('pinned', models.BooleanField(default=False, verbose_name='прекреплен ли данный комментарий?')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментраии',
            },
        ),
    ]
